### ISSUE TITLE
command giving no results

### ISSUE THREAD

**Issue by balook** [incogbyte/shosubgo#1]
go run main.go  -d google.com -s <api> => 
no result but only blank

**Comment by sridharm17** [comment]
go run main.go -d twitch.tv -s APIKEY -v
use -v flag,If you have shodan credits,you get output

**Comment by incogbyte** [comment]
You verify with -v ? Your api key have credits ? 


<img width="403" alt="image" src="https://user-images.githubusercontent.com/53656948/206858277-2658c8c4-085f-4f21-8c5a-edbbb622210c.png">

```
$ shosubgo -d "example.com" -s "<key>" -v 
```
