### ISSUE TITLE
Brand new osx install getting error

### ISSUE THREAD

**Issue by pandaiolo** [incogbyte/shosubgo#10]
Hi, sorry if this is a dumb question, I have no prior experience with the go ecosystem.

Before trying to install shosubgo, I tried to install go with `brew install go`, then I reinstalled go using the official package, but still getting the same issue.

Here is what I see when I try to install:

```
macbook shosubgo % go install github.com/incogbyte/shosubgo@latest # no output, wherever I type this
macbook shosubgo % go install
main.go:9:2: package apishodan is not in GOROOT (/opt/homebrew/Cellar/go/1.19.5/libexec/src/apishodan)
```

The main issue is that the installation command doesn't do anything nor display any error. The second one is when I cloned the GitHub repo and tried to run go install there fwiw.

Thanks!

**Comment by incogbyte** [comment]
Hi! 

I tried to reproduce the steps, and it's work for me

<img width="680" alt="image" src="https://user-images.githubusercontent.com/53656948/218852951-b09432e3-b8d2-4f5a-8e40-106818305e54.png">

Your go env is correct ?

**Comment by pandaiolo** [comment]
Thanks for helping!

How can I assess hat my go env is correct? I don't know anything about the go ecosystem.

**Comment by Guymosciski** [comment]
@pandaiolo i would recommend to watch this video https://www.youtube.com/watch?v=87hPDYriyxU&ab_channel=PentestGuy it is the simplest way to install go. after installing go then restart your linux machine. then try to use 
go version 
see if there is a response with version number. now 
go install -v github.com/incogbyte/shosubgo@latest
then change your directory to cd go/bin
sudo cp shosubgo /usr/local/go/bin
now you can use shosubgo command under any folder in your linux machine 
hope it resolves your issue

**Comment by incogbyte** [comment]
Thanks @Guymosciski, @pandaiolo this video will work if you follow. i'll will clode the the issue.
