### ISSUE TITLE
Credit: 0

### ISSUE THREAD

**Issue by RussellMurad** [incogbyte/shosubgo#4]
I've tried to run this script using two shodan account API key.
But each time it says, "Credit 0, Scan Credits: 0".

![image](https://user-images.githubusercontent.com/6575563/91013143-11720280-e609-11ea-89ec-d9e38927f714.png)

**Comment by DrRek** [comment]
same

**Comment by rodnt** [comment]
your api keys has credit ?

**Comment by incogbyte** [comment]
Without credits you cant scan anything.  Use with -v to verify

```
shosubgo -d example.com -v -s "<your shodan key>"

```

<img width="403" alt="image" src="https://user-images.githubusercontent.com/53656948/206857964-26347a4d-ef40-4f26-ae77-e7d3e35fc336.png">
