### ISSUE TITLE
error in scanning

### ISSUE THREAD

**Issue by danieltamang806** [incogbyte/shosubgo#5]
module declares its path as: shosubgo
	        but was required as: github.com/incogbyte/shosubgo

**Comment by incogbyte** [comment]
Fixed

install with 

```
go install github.com/incogbyte/shosubgo@latest

```
<img width="659" alt="image" src="https://user-images.githubusercontent.com/53656948/206857403-92cd8509-2f59-4467-8097-9bef70a38691.png">
