### ISSUE TITLE
Relative import no longer supported in Go apparently

### ISSUE THREAD

**Issue by zer0koan** [incogbyte/shosubgo#7]
Building from source, had to change "./apshodan" in main.go to "apishodan", then move apishodan/api.go into /usr/lib/go-1.17/src/ in order to build.

**Comment by incogbyte** [comment]
Fixed

<img width="659" alt="image" src="https://user-images.githubusercontent.com/53656948/206857344-cac44d6d-2463-4dd1-826f-43e9693529eb.png">
