### ISSUE TITLE
Can't install with go get

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [incogbyte/shosubgo#8]
```
$ go get github.com/incogbyte/shosubgo/apishodan
go get: github.com/incogbyte/shosubgo@v0.0.0-20211228204013-92c8070aade4: parsing go.mod:
        module declares its path as: shosubgo
                but was required as: github.com/incogbyte/shosubgo
```

go version go1.17.2 windows/amd64

**Comment by Ray-Aldred** [comment]
I got this too.

**Comment by y0sua** [comment]
any update?

**Comment by ItsIgnacioPortal** [comment]
> any update?

Use my fork. I fixed it:
https://github.com/ItsIgnacioPortal/shosubgo/

**Comment by SalemNabeelSalem** [comment]
@ItsIgnacioPortal did exe working on Linux ?

**Comment by ItsIgnacioPortal** [comment]
> @ItsIgnacioPortal did exe working on Linux ?

If you're on linux, it will generate a linux executable. It'll just be called "main"

**Comment by incogbyte** [comment]
Fixed guys

Just use 

```
go install github.com/incogbyte/shosubgo@latest
```

<img width="659" alt="image" src="https://user-images.githubusercontent.com/53656948/206857321-6e81a0b5-89a5-4b2c-baaf-31f4f4e0c3e4.png">
