### ISSUE TITLE
can not install with latest go version go install

### ISSUE THREAD

**Issue by Bugspiderlee** [incogbyte/shosubgo#9]
iam getting the following error

go install github.com/incogbyte/shosubgo/apishodan@latest                                                                                                                                 
go: github.com/incogbyte/shosubgo/apishodan@latest: github.com/incogbyte/shosubgo@v0.0.0-20211228204013-92c8070aade4: parsing go.mod:
        module declares its path as: shosubgo
                but was required as: github.com/incogbyte/shosubgo
is there any were around that thanks

**Comment by incogbyte** [comment]
Fixed

<img width="659" alt="image" src="https://user-images.githubusercontent.com/53656948/206857218-e99dcfa9-425e-477e-8c21-c21fa2847b35.png">
